### ISSUE TITLE
Highlight edges when hovering over them

### ISSUE THREAD

**Issue by oli-obk** [nikomatsakis/skill-tree#13]
For the const eval skill tree I added

```html
<style>
      /* the lines within the edges */
      .edge:active path,
      .edge:hover path {
        stroke: fuchsia;
        stroke-width: 3;
        stroke-opacity: 1;
      }
      /* arrows are typically drawn with a polygon */
      .edge:active polygon,
      .edge:hover polygon {
        stroke: fuchsia;
        stroke-width: 3;
        fill: fuchsia;
        stroke-opacity: 1;
        fill-opacity: 1;
      }
      /* If you happen to have text and want to color that as well... */
      .edge:active text,
      .edge:hover text {
        fill: fuchsia;
      }
</style>
```

to the mdbook contents in order to make edges get highlighted (thick and pink) when you hover over them or their arrow heads. It may be useful to have `mdbook-skill-tree` automatically generate this.

**Comment by nikomatsakis** [comment]
We could include some "additional css" in the mdbook?

**Comment by oli-obk** [comment]
In the same way that you injected the json files? I'll try that!

**Comment by nikomatsakis** [comment]
Yep. I think there's an "additional-css" property you can add. I stole it from the [mdbook-mermaid](https://github.com/badboy/mdbook-mermaid) project -- ah which reminds me that I made some bugfixes along the way I should really contribute back.

**Comment by XAMPPRocky** [comment]
I believe the `additional-css` is only available to a book and not to the actual preprocessors. I’m pretty sure though you can just include the `<style>` element in the output in a similar way the `<script>` element is currently. Though with CSS I would keep it as a separate source file that’s loaded with `include_str!`.
