### ISSUE TITLE
include a legend

### ISSUE THREAD

**Issue by nikomatsakis** [nikomatsakis/skill-tree#3]
The skill tree includes some emojis meant to show the status of each project, but folks have commented that their meaning is not immediately obvious. (See [example](https://rust-lang.github.io/wg-traits/roadmap/skill-tree.html).)

Current emojis:

- ☑️ -- completed
- 🛠️ -- assigned, in-progress
- ⌚ -- blocked
- 🙋 -- available, please volunteer!

It'd also be good I think to make other visual adjustments to help the "available!" things pop out more, etc

These emojis are set here:

https://github.com/nikomatsakis/skill-tree/blob/c16cac5f2b507ea6476fbcb63db54dbefb9ab08b/src/graphviz.rs#L73-L76

**Comment by Mcat12** [comment]
A legend can be added by simply adding a new group. To make it pop out more, we could add a field for header color:
![image](https://user-images.githubusercontent.com/4417660/81945964-c63d6200-95cc-11ea-82da-105f454e1a5b.png)

**Comment by Mcat12** [comment]
I also looked into adding tooltips for the emojis, but it looks like they need to be `href="#"` links for that to work: https://github.com/mdaines/viz.js/issues/66

**Comment by nikomatsakis** [comment]
@Mcat12 ah, good idea...
